version: '3'
services:
    app:
        image: node
        depends_on:
            - db
        ports:
            - "3000:3000"
        volumes:
            - .:/home/app/
        restart: always
        command: >
            bash -c "cd /home/app && npm install && npm start"
        depends_on: [db]
    db:
        image: mongo
        # ports:
            # - "27017:27017"
        restart: always